### ISSUE TITLE
Consider printing the path when it already exists

### ISSUE THREAD

**Issue by kergoth** [pietvanzoen/git-get#10]
Currently you print an error message to stderr and return nonzero, but don't return anything on stdout. I think there'd be value in allowing the shell alias to still take you to an already existing path from a previous `git get`, rather than only working on new ones. Admittedly, most will use autojump/fasd/z/j/whatever to get around, but for scripting purposes in particular I think it'd be useful.

**Comment by pietvanzoen** [comment]
I think I like this. I was trying to think about situations where you might not want this (and therefore could go behind a flag). But assuming the directory is there because `git get` succeeded at some point in the past I think this could be a coherent feature.

I was thinking there might be situations where the directory was created but the project not successfully cloned, but I think those situations are mostly covered.

**Comment by pietvanzoen** [comment]
@kergoth submitted a PR here https://github.com/pietvanzoen/git-get/pull/11. Let me know what you think.

**Comment by kergoth** [comment]
Looks good to me, thanks.
